import'package:flutter/material.dart';
import'urun.dart';

List<Urun>
  teknolojiUrunleri=[
    Urun("SAMSUNG GALAXY A31 128 GB AKILLI TELEFON",3000),
    Urun("SAMSUNG GALAXY S20 FE 128 GB AKILLI TELEFON",5000),
    Urun("SAMSUNG GALAXY A71 128 GB AKILLI TELEFON",4000),
    Urun("SAMSUNG GALAXY A51 FE 128 GB AKILLI TELEFON",3300),
    Urun("SAMSUNG GALAXY A21S 128 GB AKILLI TELEFON",2500),
    Urun("SAMSUNG GALAXY A72 FE 128 GB AKILLI TELEFON",5000),
  ];
List<Urun>
mutfakUrunleri=[
    Urun("KARACA BİOGRANİT BLACKGOLD NEW 7 PARÇA TENCERE SETİ",600),
    Urun("GÜRAL PORSELEN ALFA 6 KİŞİLİK YEMEK TAKIMI",266),
    Urun("FİSSLER VİTAQUİCK RED DÜDÜKLÜ TENCERE ",1500),
    Urun("KARACA SİENA 12 KİŞİLİK GOLD YEMEK TAKIMI",2000),
    Urun("KÜTAHYA PORSELEN ZEUGMA KAHVE TAKIMI",100),
    Urun("LAV DİAMOND 18 PARÇA BARDAK SETİ",70),
  ];List<Urun>
giyimUrunleri=[
    Urun("KAPÜŞONLU BASİC TUNİK",100),
    Urun("FASHİON BASKILI KAPÜŞONLU TUNİK",70),
    Urun("KAPÜŞONLU KADIN MONT",550),
    Urun("KADIN SİYAH PANTOLON",100),
    Urun("ERKEK SİYAH SLİM FİT T-SHİRT",150),
    Urun("ERKEK STANDART FİT BİSİKLET YAKA TRİKO",200),
  ];List<Urun>
kozmetikUrunleri=[
    Urun("EKLİPS MAKYAJ FIRÇASI VE SÜNGER SETİ",70),
    Urun("BENRİ VÜCUT LOSYONU",20),
    Urun("BEAULİS MİNİ KONTÜR PALETİ",16),
    Urun("CİTY COLOR COPPER FAR PALETİ",33),
    Urun("BEAULİS FAKE IT MSKARA HACİMLİ VE UZUN KİRPİKLER",25),
    Urun("CELENAS SEA BUCKTHORN YÜZ YIKAMA JELİ",55),
  ];List<Urun>
evTekstilUrunleri=[
    Urun("SLEEP PEOPLE 3D BAMBOO VİSCO ÇİFT KİŞİLİK YATAK",1700),
    Urun("TAÇ KETEN PİLESİZ TÜL",80),
    Urun("YATAŞ BEDDİNG POLYAT YASTIK",45),
    Urun("YATAŞ BEDDİNG HANDY ROLL PACK YASTIK YORGAN SETİ",99),
    Urun("PAMUKKALE ALEZ YATAK KORUYUCU",150),
    Urun("ENGLİSH HOME SOFTY WELLSOFT TV BATTANİYE",60),
  ];
  List<Urun>
beyazEsyaUrunleri=[
    Urun("PROFİLO A++ ENERJİ SINIFI BUZDOLABI",8500),
    Urun("BOSCH A+ ENERJİ SINIFI BUZDOLABI",3800),
    Urun("VESTEL A++ ENERJİ SINIFI BUZDOLABI",6200),
    Urun("BOSCH 9KG ÇAMAŞIR MAKİNESİ",3500),
    Urun("ARÇELİK 9KG ÇAMAŞIR MAKİNESİ",3600),
    Urun("VESTEL BM 5001 BULAŞIK MAKİNESİ",3990),
  ];

